version: '3.7'
services:
  # Configure the database
  database:
    image: mysql:5.7
    environment:
            - MYSQL_ROOT_PASSWORD=somerootpass
            - MYSQL_PASSWORD=somepass
            - MYSQL_DATABASE=dockerizeme_db
            - MYSQL_USER=someuser
  web:
        build: .
        ports:
            - 8080:80
        volumes:
            - .:/var/www