version: '3'
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: news_parser
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    
  web:
    build: .
    ports:
          - 8080:80
